package constants

const (
	TuneFindApiBaseURL     = "https://www.tunefind.com/api/frontend/"
	TunefindBaseURL        = "https://tunefind.com"
	TmdbApiKey             = "api_key=2caaa89866fe5b08fcab57571825d956"
	TmdbImageBaseUrl       = "https://image.tmdb.org/t/p/"
	TmdbShowBrowse         = "https://api.themoviedb.org/3/search/tv?" + TmdbApiKey + "&language=en-US&page=1&include_adult=true"
	TmdbMovieBrowse        = "https://api.themoviedb.org/3/search/movie?" + TmdbApiKey + "&language=en-US&page=1&include_adult=true"
	TmdbMovieSearch        = "https://api.themoviedb.org/3/movie/"
	TmdbShowSearch         = "https://api.themoviedb.org/3/tv/"
	TmdbSeasonSearch       = "https://api.themoviedb.org/3/tv/"
	TmdbEpisodeSearch      = "https://api.themoviedb.org/3/tv/"
	TuneFindBrowseAllMovie = "https://www.tunefind.com/api/frontend/movie/browse"
	TuneFindBrowseAllShow  = "https://www.tunefind.com/api/frontend/show/browse"
	TuneFindBrowseAllGame  = "https://www.tunefind.com/api/frontend/game/browse"
	TuneFindShowHome       = "https://www.tunefind.com/api/frontend/show"
	TuneFindMovieHome      = "https://www.tunefind.com/api/frontend/movie"
	TuneFindGameHome       = "https://www.tunefind.com/api/frontend/game"
	TuneFindMovieSearch    = "https://www.tunefind.com/api/frontend/movie/"
	TuneFindShowSearch     = "https://www.tunefind.com/api/frontend/show/"
	TuneFindSeasonSearch   = "https://www.tunefind.com/api/frontend/show/"
	TuneFindEpisodeSearch  = "https://www.tunefind.com/api/frontend/episode/"
	TuneFindTrending       = "https://www.tunefind.com/api/frontend/trending/now"
)
